### PR TITLE
use socketio api

### PR DESCRIPTION
**Pull request by schnabel**
Hi,

here is my PR addressing [the polling problem](https://github.com/willholdoway/hifiberry/issues/3). It is probably not complete (At least shutdown is not addressed yet) but I thought you might want to have a look at it. I opened PRs at the upstream repositories. [pyhifiberry](https://github.com/dgomes/pyhifiberry/pull/4) wants to accept the PR if the hifiberry also do :-). If you want you can test the stuff on your local machine.

### CODE REVIEW

**Comment by willholdoway** [comment]
looks good

**Comment by willholdoway** [comment]
@schnabel can you let me know when upstream have accepted and I will merge?

**Comment by schnabel** [comment]
Sure.

**Comment by willholdoway** [comment]
@schnabel has this still not been accepted upstream?

**Comment by schnabel** [comment]
@willholdoway unfortunately not. It might help if somebody offers to review :-).

**Comment by schnabel** [comment]
@willholdoway @dgomes the PRs on the hifiberry side have been merged :-). The next release will hopefully allow us to move on!

**Comment by schnabel** [comment]
I have been happy too early :-(. There is a problem with an audiocontrol2 plugin that might be a show stopper. I will let you know when there are news on this.

**Comment by dgomes** [comment]
how's such ?

**Comment by schnabel** [comment]
@willholdoway @dgomes I have been able to solve the problems with the audiocontrol2 plugin. And the hifiberry guys have released a new version of hifiberryos which contains the socketio api! So we can finally move on!

**Comment by willholdoway** [comment]
> @willholdoway @dgomes I have been able to solve the problems with the audiocontrol2 plugin. And the hifiberry guys have released a new version of hifiberryos which contains the socketio api! So we can finally move on!

Could you link me to this release please? I can’t find it.

**Comment by schnabel** [comment]
Hi,

You can use the Software update link in the webinterface of your pi or
download from here <https://www.hifiberry.com/hifiberryos/> (depends on
your type of pi). Unfortunately hifiberry only seems to offer the latest
build here.

Hope that helps, Dirk

Am So., 27. Feb. 2022 um 14:36 Uhr schrieb willholdoway <
***@***.***>:

**Comment by dgomes** [comment]
That's the issue, it says there nothing to update.

The PI is in an unreachable location, could I update through the command line?

**Comment by schnabel** [comment]
Hi @dgomes, I am assuming you mean the Software Update page of the hifiberryos webui. My guess is, you might have set the automatic updates option to 'Quick'. That way you might already have the latest version installed. You could check on the main page in the 'About' section or in the Software update page. What does it say about the software version? If it is larger than 201909xx updating should work.
If your pi is really not up to date, let me know. You can update through command line via ssh and I will try to write a little guide if you need.

**Comment by dgomes** [comment]
https://github.com/hifiberry/hifiberry-os/issues/350

**Comment by dgomes** [comment]
If you can point me to the command line option that would be great :)

**Comment by schnabel** [comment]
Ok. That is not good. We can give it a try but I am not sure if it will work with that release because under the hood it probably uses the same code. Another problem is that I don't know where they host the updater.zip :-(. I might have to build one for your pi3. I will let you know as soon as I have an updater. Please let me know if you are willing to try with a build I offer (because the build takes a few hours).

**Comment by dgomes** [comment]
No worries @schnabel I will look into getting access to the RPi3 next weekend, then I will flash the SD with the latests release.

**Comment by dgomes** [comment]
Sorry, upgraded but have not tested this PR yet

**Review by willholdoway — CHANGES_REQUESTED** [review]
Hi @schnabel, I've made a couple of changes to the way base_url is handled as I couldn't see anything in your code referencing the homeassistant configured host and port, only the defaults in your pyhifiberry module.

I've therefore added a variable here to ensure that local artwork works, let me know that you're happy.

**Comment by schnabel** [comment]
Hi @willholdoway, I hope that I will find a slot to have a look at the end of the week. I am still waiting for Diogos go on the pyhifiberry side.

**Comment by willholdoway** [comment]
Hi @schnabel, I've nudged @dgomes on the pyhifiberry side too and also made a couple of recommendations there. Thanks

**Comment by schnabel** [comment]
@willholdoway Your changes are ok to me. But as mentioned on the pyhifiberry PR, there is no need to pass it there.

**Pull request merged**
